main: net.fightpvp.main.Fight
name: HDKits
author: TheHDgamerBR
version: 1.0
description: Ola :3
commands:
  setwarp:
  delwarp:
  setitem:
  suicide:
  warp:
  pvp:
  archer:
  stomper:
  switcher:
  kangaroo:
  endermage:
  checkpoint:
  fisherman:
  poseidon:
  timelord:
  gladiator:
  setspawn:
  sopa:
  invsee:
  kits:
  turtle:
  snail:
  tag:
  thor:
  tank:
  grappler:
  copycat:
  specialist:
  monk:
  anchor:
  hulk:
  urgal:
  kick:
  ban:
  pardon:
  new:
  repair:
  kill:
  admin:
  s:
  c:
  dia:
  noite:
  loja:
  spawn:
  setspawn: